- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: Enable the RPM Fusion repository
  dnf:
    name:
      - 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
    disable_gpg_check: yes
    
- name: Enable the RPM Fusion Non-free repository
  dnf:
    name:
      - 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
    disable_gpg_check: yes

- name: Add the Azul Java Repository
  dnf:
    name:
      - 'https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm'
    state: present
    disable_gpg_check: yes

- name: Install packages
  package:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      # nvidia modules starts here
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      # nvidia modules ends here
      - snapd
      - vulkan
      - aria2
      - git
      - git-lfs
      - neovim
      - htop
      - zulu8-jdk
      - java-11-openjdk-devel
      - golang
      - nodejs
      - yarn
      - code
      - google-chrome-stable
      - python3-psutil # ansible dconf module
      - python-pip
      - evolution
      - evolution-ews
      - seahorse
      - seahorse-nautilus
      - texlive
      - latexmk
      - texlive-chktex
      - texlive-latexindent
      - texlive-wrapfig
      - texlive-sourcesanspro
      - texlive-fontawesome
      - texlive-tcolorbox
      - texlive-clrscode3e
      - gimp
      - inkscape
      - gcc
      - gcc-c++
      - llvm
      - clang
      - lldb
      - make
      - cmake
      - ffmpeg
      - dino
      - resilio-sync
      - emacs
      - blender
      - celluloid
      - foliate
      - sublime-text
      - freecad
      - remmina
      - deadbeef
      - krita
      - renderdoc
      - LuxRender
      - meshlab
      - godot
      - rawtherapee
      - darktable
      - radare2
      - cutter-re
      - yubikey-manager
      - wings
      - glfw
      - p7zip
      - p7zip-plugins
      - lvm2
      - valgrind
      - perf
      - transmission
      - gnome-todo
      - fish
      # gstreamer
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-good-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-plugins-ugly-free
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-extras
      # the following depends on jackctl
      #- ardour6
      #- supercollider
      
- name: Create a symbolic link
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
    
- name: install starship
  shell: curl -fsSL https://starship.rs/install.sh | bash -s -- -y
  args:
    creates: '/usr/local/bin/starship'
