- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: Enable the RPM Fusion repository
  dnf:
    name:
      - 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
    disable_gpg_check: yes

- name: Add the Resilio Sync repository
  dnf:
    name:
      - 'https://linux-packages.resilio.com/resilio-sync/rpm/{{ ansible_distribution_major_version }}'
    state: present
    disable_gpg_check: yes

- name: Add the Sublime Text repository
  dnf:
    name:
      - 'https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo'
    state: present
    disable_gpg_check: yes

- name: Install packages
  package:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - xorg-x11-drv-nvidia-cuda-libs
      - vulkan
      - aria2
      - git
      - git-lfs
      - neovim
      - htop
      - java-11-openjdk-devel
      - golang
      - nodejs
      - yarn
      - code
      - google-chrome-stable
      - python3-psutil # ansible dconf module
      - evolution
      - evolution-ews
      - seahorse
      - seahorse-nautilus
      - texlive
      - latexmk
      - texlive-chktex
      - texlive-latexindent
      - texlive-wrapfig
      - texlive-sourcesanspro
      - texlive-fontawesome
      - texlive-tcolorbox
      - texlive-clrscode3e
      - gimp
      - inkscape
      - gcc
      - gcc-c++
      - llvm
      - clang
      - lldb
      - make
      - cmake
      - ffmpeg
      - dino
      - resilio-sync
      - emacs
      - blender
      - celluloid
      - foliate
      - sublime-text
      - freecad
      - remmina
      - deadbeef
      - krita
      - supercollider
      - renderdoc
      - luxrender
      - meshlab
      - godot
      - rawtherapee
      - darktable
      - radare2
      - yubikey-manager
      - wings
      - lxd
      - ardour6
      - glfw
      - p7zip
      - lvm2